### ISSUE TITLE
ThreadSanitizer: data race mio-0.6.4/src/poll.rs:728 in mio::poll::{{impl}}::prepend_readiness_node

### ISSUE THREAD

**Issue by brunoqc** [carllerche/mio#547]
When I run my code using `RUSTFLAGS="-Z sanitizer=thread" cargo run` I get a data race. I'm assuming it's in mio's code since it was the first thing in the trace.

mio 0.6.4
rustc 1.17.0-nightly (0e7727795 2017-02-19)

```
==================
WARNING: ThreadSanitizer: data race (pid=20455)
  Write of size 8 at 0x7c540000ee48 by thread T11 (mutexes: read M163, write M182):
    #0 mio::poll::{{impl}}::prepend_readiness_node /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:728 (pubsub+0x0000001c408d)
    #1 mio::poll::{{impl}}::queue_for_processing /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:484 (pubsub+0x0000001c362a)
    #2 mio::poll::{{impl}}::set_readiness /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:465 (pubsub+0x0000001c3523)
    #3 mio::poll::{{impl}}::set_readiness /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:404 (pubsub+0x0000001c3189)
    #4 mio::channel::{{impl}}::inc /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:202 (pubsub+0x0000001c6c0a)
    #5 mio::channel::{{impl}}::send::{{closure}}<ws::communication::Command> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:141 (pubsub+0x000000098424)
    #6 core::result::{{impl}}::and_then<(),mio::channel::SendError<ws::communication::Command>,(),closure> /checkout/src/libcore/result.rs:601 (pubsub+0x0000000aafa8)
    #7 mio::channel::{{impl}}::send<ws::communication::Command> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:138 (pubsub+0x0000000983cf)
    #8 ws::communication::{{impl}}::send<collections::string::String> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/communication.rs:74 (pubsub+0x000000071bd9)
    #9 pubsub::multichan::{{impl}}::push /home/bbigras/dev/rust/pubsub/src/multichan.rs:35 (pubsub+0x0000000f564c)
    #10 pubsub::serveur_http::{{impl}}::handle /home/bbigras/dev/rust/pubsub/src/serveur_http.rs:102 (pubsub+0x0000000f64c2)
    #11 iron::middleware::{{impl}}::handle /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318 (pubsub+0x00000021d499)
    #12 iron::middleware::{{impl}}::continue_from_handler /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:282 (pubsub+0x00000021ce7c)
    #13 iron::middleware::{{impl}}::continue_from_before /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:265 (pubsub+0x00000021cc9f)
    #14 iron::middleware::{{impl}}::handle /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:200 (pubsub+0x00000021c2ab)
    #15 iron::middleware::{{impl}}::handle /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318 (pubsub+0x00000021d499)
    #16 router::router::{{impl}}::handle_method /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:199 (pubsub+0x0000001f0a6c)
    #17 router::router::{{impl}}::handle /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:212 (pubsub+0x0000001f0ccd)
    #18 iron::iron::{{impl}}::handle<router::router::Router> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176 (pubsub+0x0000000e44b7)
    #19 hyper::server::{{impl}}::keep_alive_loop<iron::iron::RawHandler<router::router::Router>,std::io::buffered::BufWriter<&mut hyper::net::HttpStream>> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:341 (pubsub+0x00000008a2c9)
    #20 hyper::server::{{impl}}::handle_connection<iron::iron::RawHandler<router::router::Router>,hyper::net::HttpStream> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:287 (pubsub+0x00000008a925)
    #21 hyper::server::handle::{{closure}}<iron::iron::RawHandler<router::router::Router>,hyper::net::HttpListener> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:246 (pubsub+0x0000000d0b07)
    #22 hyper::server::listener::spawn_with::{{closure}}<hyper::net::HttpListener,closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/listener.rs:50 (pubsub+0x0000000d0fac)
    #23 std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296 (pubsub+0x0000000f0924)
    #24 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:450 (pubsub+0x0000000933dd)
    #25 panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #26 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361 (pubsub+0x000000091eec)
    #27 std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:357 (pubsub+0x000000092e5f)
    #28 alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:638 (pubsub+0x0000000c565e)
    #29 alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:648 (pubsub+0x0000003365d4)
    #30 std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21 (pubsub+0x0000003365d4)
    #31 std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84 (pubsub+0x0000003365d4)

  Previous write of size 8 at 0x7c540000ee48 by main thread:
    #0 mio::poll::{{impl}}::take /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:872 (pubsub+0x0000001c48c5)
    #1 mio::poll::{{impl}}::next::{{closure}} /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:853 (pubsub+0x0000001c481e)
    #2 core::option::{{impl}}::map<&mut mio::poll::ReadinessNode,(),closure> /checkout/src/libcore/option.rs:383 (pubsub+0x0000001ba385)
    #3 mio::poll::{{impl}}::next /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:853 (pubsub+0x0000001c47b2)
    #4 mio::poll::{{impl}}::poll /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:586 (pubsub+0x0000001c3aac)
    #5 mio::poll::{{impl}}::poll /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:251 (pubsub+0x0000001c2d6c)
    #6 ws::io::{{impl}}::event_loop<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:355 (pubsub+0x0000000774b6)
    #7 ws::io::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:342 (pubsub+0x00000007cd9f)
    #8 ws::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #9 ws::{{impl}}::listen<closure,&str> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #10 ws::listen<&str,closure,pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #11 pubsub::serveur_ws::listen_ws /home/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #12 pubsub::main /home/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #13 panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #14 __libc_start_main <null> (libc.so.6+0x000000020290)

  Location is heap block of size 72 at 0x7c540000ee20 allocated by main thread:
    #0 malloc /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:591 (pubsub+0x00000015ee2f)
    #1 alloc::heap::allocate /checkout/src/liballoc/heap.rs:59 (pubsub+0x0000001c01f3)
    #2 alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:138 (pubsub+0x0000001c0199)
    #3 alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:236 (pubsub+0x0000001c3ee2)
    #4 mio::poll::{{impl}}::new_readiness_node /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:699 (pubsub+0x0000001c3ee2)
    #5 mio::poll::{{impl}}::new /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:414 (pubsub+0x0000001c31e4)
    #6 mio::poll::{{impl}}::new /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:414 (pubsub+0x0000001c31e4)
    #7 mio::poll::{{impl}}::new /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:366 (pubsub+0x0000001c2fcd)
    #8 mio::channel::{{impl}}::register /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:257 (pubsub+0x0000001c6fa8)
    #9 mio::channel::{{impl}}::register<ws::communication::Command> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:176 (pubsub+0x0000000d9ae1)
    #10 mio::poll::{{impl}}::register<mio::channel::Receiver<ws::communication::Command>> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:196 (pubsub+0x00000008ba2c)
    #11 ws::io::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:338 (pubsub+0x00000007cc84)
    #12 ws::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #13 ws::{{impl}}::listen<closure,&str> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #14 ws::listen<&str,closure,pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #15 pubsub::serveur_ws::listen_ws /home/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #16 pubsub::main /home/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #17 panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #18 __libc_start_main <null> (libc.so.6+0x000000020290)

  Mutex M163 (0x7c540000ef10) created at:
    #0 pthread_rwlock_wrlock /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1257 (pubsub+0x0000001370cc)
    #1 std::sys::imp::rwlock::{{impl}}::write /checkout/src/libstd/sys/unix/rwlock.rs:82 (pubsub+0x0000000912f6)
    #2 std::sys_common::rwlock::{{impl}}::write /checkout/src/libstd/sys_common/rwlock.rs:51 (pubsub+0x00000008ca69)
    #3 std::sync::rwlock::{{impl}}::write<collections::vec::Vec<pubsub::multichan::Mchan>> /checkout/src/libstd/sync/rwlock.rs:217 (pubsub+0x000000099765)
    #4 pubsub::serveur_ws::{{impl}}::on_open /home/bbigras/dev/rust/pubsub/src/serveur_ws.rs:69 (pubsub+0x0000000f726b)
    #5 ws::connection::{{impl}}::write_handshake<pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:464 (pubsub+0x0000000a2c80)
    #6 ws::connection::{{impl}}::write<pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:798 (pubsub+0x0000000a5714)
    #7 ws::io::{{impl}}::handle_event<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:544 (pubsub+0x000000078f58)
    #8 ws::io::{{impl}}::event_loop<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:375 (pubsub+0x000000077981)
    #9 ws::io::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:342 (pubsub+0x00000007cd9f)
    #10 ws::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #11 ws::{{impl}}::listen<closure,&str> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #12 ws::listen<&str,closure,pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #13 pubsub::serveur_ws::listen_ws /home/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #14 pubsub::main /home/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #15 panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #16 __libc_start_main <null> (libc.so.6+0x000000020290)

  Mutex M182 (0x7c4c0000ed60) created at:
    #0 pthread_mutex_init /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1119 (pubsub+0x000000138416)
    #1 std::sys::imp::mutex::{{impl}}::init /checkout/src/libstd/sys/unix/mutex.rs:60 (pubsub+0x0000000910cf)
    #2 std::sys_common::mutex::{{impl}}::init /checkout/src/libstd/sys_common/mutex.rs:33 (pubsub+0x00000008c399)
    #3 std::sync::mutex::{{impl}}::new<ws::communication::Sender> /checkout/src/libstd/sync/mutex.rs:174 (pubsub+0x000000097b64)
    #4 pubsub::multichan::{{impl}}::add /home/bbigras/dev/rust/pubsub/src/multichan.rs:23 (pubsub+0x0000000f5355)
    #5 pubsub::serveur_ws::{{impl}}::on_open /home/bbigras/dev/rust/pubsub/src/serveur_ws.rs:70 (pubsub+0x0000000f7303)
    #6 ws::connection::{{impl}}::write_handshake<pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:464 (pubsub+0x0000000a2c80)
    #7 ws::connection::{{impl}}::write<pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:798 (pubsub+0x0000000a5714)
    #8 ws::io::{{impl}}::handle_event<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:544 (pubsub+0x000000078f58)
    #9 ws::io::{{impl}}::event_loop<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:375 (pubsub+0x000000077981)
    #10 ws::io::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:342 (pubsub+0x00000007cd9f)
    #11 ws::{{impl}}::run<closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #12 ws::{{impl}}::listen<closure,&str> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #13 ws::listen<&str,closure,pubsub::serveur_ws::ClientWs> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #14 pubsub::serveur_ws::listen_ws /home/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #15 pubsub::main /home/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #16 panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #17 __libc_start_main <null> (libc.so.6+0x000000020290)

  Thread T11 (tid=20872, running) created by thread T2 at:
    #0 pthread_create /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:902 (pubsub+0x0000001389b7)
    #1 std::sys::imp::thread::{{impl}}::new /checkout/src/libstd/sys/unix/thread.rs:72 (pubsub+0x0000003362d5)
    #2 std::thread::spawn<closure,()> /checkout/src/libstd/thread/mod.rs:412 (pubsub+0x000000091fdd)
    #3 hyper::server::listener::spawn_with<hyper::net::HttpListener,closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/listener.rs:45 (pubsub+0x0000000d0d7c)
    #4 hyper::server::listener::{{impl}}::accept<hyper::net::HttpListener,closure> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/listener.rs:31 (pubsub+0x0000000cc67a)
    #5 hyper::server::handle::{{closure}}<iron::iron::RawHandler<router::router::Router>,hyper::net::HttpListener> /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:248 (pubsub+0x0000000d0c02)
    #6 std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296 (pubsub+0x0000000f0898)
    #7 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:450 (pubsub+0x0000000932d1)
    #8 panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #9 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361 (pubsub+0x000000091e80)
    #10 std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:357 (pubsub+0x000000092cbe)
    #11 alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:638 (pubsub+0x0000000c55d8)
    #12 alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:648 (pubsub+0x0000003365d4)
    #13 std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21 (pubsub+0x0000003365d4)
    #14 std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84 (pubsub+0x0000003365d4)

SUMMARY: ThreadSanitizer: data race /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:728 in mio::poll::{{impl}}::prepend_readiness_node
==================
```

**Comment by carllerche** [comment]
Thanks for the report. There indeed was an issue. It has been fixed on master as part of: https://github.com/carllerche/mio/commit/43a69f218957ea7f43bb821734dbfbad09078c6b

If you could try that commit and see if it fixes the problem, it would be appreciated.

**Comment by brunoqc** [comment]
It seems I still have the problem with 43a69f218957ea7f43bb821734dbfbad09078c6b.

```
==================
WARNING: ThreadSanitizer: data race (pid=23030)
  Write of size 8 at 0x7c540000ee48 by thread T15 (mutexes: read M163, write M164):
    #0 mio::poll::ReadinessQueue::prepend_readiness_node::h553699cbe5e04d43 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:728 (pubsub+0x0000001c408d)
    #1 mio::poll::RegistrationInner::queue_for_processing::h0581278bfd840f4f /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:484 (pubsub+0x0000001c362a)
    #2 mio::poll::RegistrationInner::set_readiness::h1b4f3170befbb46d /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:465 (pubsub+0x0000001c3523)
    #3 mio::poll::SetReadiness::set_readiness::h6b18f724398c9d25 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:404 (pubsub+0x0000001c3189)
    #4 mio::channel::SenderCtl::inc::haec45b62c8464288 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:202 (pubsub+0x0000001c6c0a)
    #5 _$LT$mio..channel..SyncSender$LT$T$GT$$GT$::send::_$u7b$$u7b$closure$u7d$$u7d$::he5ec54ddd74bdc79 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:141 (pubsub+0x000000098424)
    #6 _$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::and_then::h10a6ad4ea0c0d99c /checkout/src/libcore/result.rs:601 (pubsub+0x0000000aafa8)
    #7 _$LT$mio..channel..SyncSender$LT$T$GT$$GT$::send::h453ab5e95ef484a8 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:138 (pubsub+0x0000000983cf)
    #8 ws::communication::Sender::send::he0956fc986a89b50 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/communication.rs:74 (pubsub+0x000000071bd9)
    #9 pubsub::multichan::Mchan::push::hd573fce33e103995 /home/LUXO/bbigras/dev/rust/pubsub/src/multichan.rs:35 (pubsub+0x0000000f564c)
    #10 _$LT$pubsub..serveur_http..PubHandler$u20$as$u20$iron..middleware..Handler$GT$::handle::hfc072f7e792a739d /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_http.rs:102 (pubsub+0x0000000f64c2)
    #11 _$LT$alloc..boxed..Box$LT$iron..middleware..Handler$u20$$u2b$$u20$$u27$static$GT$$u20$as$u20$iron..middleware..Handler$GT$::handle::h6a9416c5da272a96 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318 (pubsub+0x00000021d499)
    #12 iron::middleware::Chain::continue_from_handler::h9b0568c24ab0c7cc /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:282 (pubsub+0x00000021ce7c)
    #13 iron::middleware::Chain::continue_from_before::h0f725c8485d6e332 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:265 (pubsub+0x00000021cc9f)
    #14 _$LT$iron..middleware..Chain$u20$as$u20$iron..middleware..Handler$GT$::handle::hd378ccfc65132786 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:200 (pubsub+0x00000021c2ab)
    #15 _$LT$alloc..boxed..Box$LT$iron..middleware..Handler$u20$$u2b$$u20$$u27$static$GT$$u20$as$u20$iron..middleware..Handler$GT$::handle::h6a9416c5da272a96 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318 (pubsub+0x00000021d499)
    #16 router::router::Router::handle_method::hcce6b4baa2b1a07a /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:199 (pubsub+0x0000001f0a6c)
    #17 _$LT$router..router..Router$u20$as$u20$iron..middleware..Handler$GT$::handle::hcdd48c4c09efd7aa /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:212 (pubsub+0x0000001f0ccd)
    #18 _$LT$iron..iron..RawHandler$LT$H$GT$$u20$as$u20$hyper..server..Handler$GT$::handle::hf56f1f7399628e7a /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176 (pubsub+0x0000000e44b7)
    #19 _$LT$hyper..server..Worker$LT$H$GT$$GT$::keep_alive_loop::he17c939708f46b4f /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:341 (pubsub+0x00000008a2c9)
    #20 _$LT$hyper..server..Worker$LT$H$GT$$GT$::handle_connection::hd271afe1432fb877 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:287 (pubsub+0x00000008a925)
    #21 hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::h739e18b6d4272fb8 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:246 (pubsub+0x0000000d0b07)
    #22 hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::hf00bdfa2db5ea98c /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/listener.rs:50 (pubsub+0x0000000d0fac)
    #23 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb980021c11f2330a /checkout/src/libstd/panic.rs:296 (pubsub+0x0000000f0924)
    #24 std::panicking::try::do_call::ha9a1ae68fcb0f019 /checkout/src/libstd/panicking.rs:450 (pubsub+0x0000000933dd)
    #25 __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #26 std::panic::catch_unwind::h1271c1b6c757d20f /checkout/src/libstd/panic.rs:361 (pubsub+0x000000091eec)
    #27 std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hbe11baceec3a8155 /checkout/src/libstd/thread/mod.rs:357 (pubsub+0x000000092e5f)
    #28 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h42d8aa6447008c62 /checkout/src/liballoc/boxed.rs:638 (pubsub+0x0000000c565e)
    #29 alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:648 (pubsub+0x0000003365d4)
    #30 std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21 (pubsub+0x0000003365d4)
    #31 std::sys::imp::thread::Thread::new::thread_start::h2c901daa88f3cb32 /checkout/src/libstd/sys/unix/thread.rs:84 (pubsub+0x0000003365d4)

  Previous write of size 8 at 0x7c540000ee48 by main thread:
    #0 mio::poll::ReadyRef::take::h7e2b44f5b8b82c52 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:872 (pubsub+0x0000001c48c5)
    #1 _$LT$mio..poll..ReadyList$u20$as$u20$core..iter..iterator..Iterator$GT$::next::_$u7b$$u7b$closure$u7d$$u7d$::h14db40af9ffbc5a8 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:853 (pubsub+0x0000001c481e)
    #2 _$LT$core..option..Option$LT$T$GT$$GT$::map::h66c3c9e9d9dde808 /checkout/src/libcore/option.rs:383 (pubsub+0x0000001ba385)
    #3 _$LT$mio..poll..ReadyList$u20$as$u20$core..iter..iterator..Iterator$GT$::next::hc57263a607cc871f /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:853 (pubsub+0x0000001c47b2)
    #4 mio::poll::ReadinessQueue::poll::ha4582aff677ad58e /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:586 (pubsub+0x0000001c3aac)
    #5 mio::poll::Poll::poll::h88738926af248a49 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:251 (pubsub+0x0000001c2d6c)
    #6 _$LT$ws..io..Handler$LT$F$GT$$GT$::event_loop::ha47c28576e994db6 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:355 (pubsub+0x0000000774b6)
    #7 _$LT$ws..io..Handler$LT$F$GT$$GT$::run::h99e1cd80c8146da5 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:342 (pubsub+0x00000007cd9f)
    #8 _$LT$ws..WebSocket$LT$F$GT$$GT$::run::hda95d3039f68f2d9 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #9 _$LT$ws..WebSocket$LT$F$GT$$GT$::listen::h955f903b0018da09 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #10 ws::listen::hdb1e06bf70161e00 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #11 pubsub::serveur_ws::listen_ws::hfbbfb4f08624a769 /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #12 pubsub::main::heea09b5a8c6e3f83 /home/LUXO/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #13 __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #14 __libc_start_main <null> (libc.so.6+0x000000020290)

  Location is heap block of size 72 at 0x7c540000ee20 allocated by main thread:
    #0 malloc /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:591 (pubsub+0x00000015ee2f)
    #1 alloc::heap::allocate::hb49e39ab82f954fa /checkout/src/liballoc/heap.rs:59 (pubsub+0x0000001c01f3)
    #2 alloc::heap::exchange_malloc::h55adee8e9fba9338 /checkout/src/liballoc/heap.rs:138 (pubsub+0x0000001c0199)
    #3 alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:236 (pubsub+0x0000001c3ee2)
    #4 mio::poll::ReadinessQueue::new_readiness_node::h3c868c8ccfb5c87e /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:699 (pubsub+0x0000001c3ee2)
    #5 mio::poll::RegistrationInner::new::h202e75cb6d9a7eca /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:414 (pubsub+0x0000001c31e4)
    #6 mio::poll::RegistrationInner::new::h202e75cb6d9a7eca /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:414 (pubsub+0x0000001c31e4)
    #7 mio::poll::Registration::new::h849cc79548d84c5e /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:366 (pubsub+0x0000001c2fcd)
    #8 _$LT$mio..channel..ReceiverCtl$u20$as$u20$mio..io..Evented$GT$::register::hd351d00f91d03c68 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:257 (pubsub+0x0000001c6fa8)
    #9 _$LT$mio..channel..Receiver$LT$T$GT$$u20$as$u20$mio..io..Evented$GT$::register::h89f89e6ec7991368 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/channel.rs:176 (pubsub+0x0000000d9ae1)
    #10 mio::poll::Poll::register::h695a2d56aecea087 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:196 (pubsub+0x00000008ba2c)
    #11 _$LT$ws..io..Handler$LT$F$GT$$GT$::run::h99e1cd80c8146da5 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:338 (pubsub+0x00000007cc84)
    #12 _$LT$ws..WebSocket$LT$F$GT$$GT$::run::hda95d3039f68f2d9 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #13 _$LT$ws..WebSocket$LT$F$GT$$GT$::listen::h955f903b0018da09 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #14 ws::listen::hdb1e06bf70161e00 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #15 pubsub::serveur_ws::listen_ws::hfbbfb4f08624a769 /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #16 pubsub::main::heea09b5a8c6e3f83 /home/LUXO/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #17 __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #18 __libc_start_main <null> (libc.so.6+0x000000020290)

  Mutex M163 (0x7c540000ef10) created at:
    #0 pthread_rwlock_wrlock /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1257 (pubsub+0x0000001370cc)
    #1 std::sys::imp::rwlock::RWLock::write::hf332d8e5051ca699 /checkout/src/libstd/sys/unix/rwlock.rs:82 (pubsub+0x0000000912f6)
    #2 std::sys_common::rwlock::RWLock::write::he40b69ab44892b76 /checkout/src/libstd/sys_common/rwlock.rs:51 (pubsub+0x00000008ca69)
    #3 _$LT$std..sync..rwlock..RwLock$LT$T$GT$$GT$::write::h9a7a2dd7f3f95e80 /checkout/src/libstd/sync/rwlock.rs:217 (pubsub+0x000000099765)
    #4 _$LT$pubsub..serveur_ws..ClientWs$u20$as$u20$ws..handler..Handler$GT$::on_open::ha3dadc1bd6bcb4ff /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_ws.rs:69 (pubsub+0x0000000f726b)
    #5 _$LT$ws..connection..Connection$LT$H$GT$$GT$::write_handshake::h9bc689b777c7e20b /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:464 (pubsub+0x0000000a2c80)
    #6 _$LT$ws..connection..Connection$LT$H$GT$$GT$::write::h6dabfec8f3fd863f /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:798 (pubsub+0x0000000a5714)
    #7 _$LT$ws..io..Handler$LT$F$GT$$GT$::handle_event::h87a677e518e743c9 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:544 (pubsub+0x000000078f58)
    #8 _$LT$ws..io..Handler$LT$F$GT$$GT$::event_loop::ha47c28576e994db6 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:375 (pubsub+0x000000077981)
    #9 _$LT$ws..io..Handler$LT$F$GT$$GT$::run::h99e1cd80c8146da5 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:342 (pubsub+0x00000007cd9f)
    #10 _$LT$ws..WebSocket$LT$F$GT$$GT$::run::hda95d3039f68f2d9 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #11 _$LT$ws..WebSocket$LT$F$GT$$GT$::listen::h955f903b0018da09 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #12 ws::listen::hdb1e06bf70161e00 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #13 pubsub::serveur_ws::listen_ws::hfbbfb4f08624a769 /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #14 pubsub::main::heea09b5a8c6e3f83 /home/LUXO/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #15 __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #16 __libc_start_main <null> (libc.so.6+0x000000020290)

  Mutex M164 (0x7c4c0000ed00) created at:
    #0 pthread_mutex_init /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1119 (pubsub+0x000000138416)
    #1 std::sys::imp::mutex::Mutex::init::h87768d3e7f5ef397 /checkout/src/libstd/sys/unix/mutex.rs:60 (pubsub+0x0000000910cf)
    #2 std::sys_common::mutex::Mutex::init::h85517a42305eba76 /checkout/src/libstd/sys_common/mutex.rs:33 (pubsub+0x00000008c399)
    #3 _$LT$std..sync..mutex..Mutex$LT$T$GT$$GT$::new::h61c6a0ef771bfa29 /checkout/src/libstd/sync/mutex.rs:174 (pubsub+0x000000097b64)
    #4 pubsub::multichan::Mchan::add::h261d93cad06f2e24 /home/LUXO/bbigras/dev/rust/pubsub/src/multichan.rs:23 (pubsub+0x0000000f5355)
    #5 _$LT$pubsub..serveur_ws..ClientWs$u20$as$u20$ws..handler..Handler$GT$::on_open::ha3dadc1bd6bcb4ff /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_ws.rs:70 (pubsub+0x0000000f7303)
    #6 _$LT$ws..connection..Connection$LT$H$GT$$GT$::write_handshake::h9bc689b777c7e20b /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:464 (pubsub+0x0000000a2c80)
    #7 _$LT$ws..connection..Connection$LT$H$GT$$GT$::write::h6dabfec8f3fd863f /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/connection.rs:798 (pubsub+0x0000000a5714)
    #8 _$LT$ws..io..Handler$LT$F$GT$$GT$::handle_event::h87a677e518e743c9 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:544 (pubsub+0x000000078f58)
    #9 _$LT$ws..io..Handler$LT$F$GT$$GT$::event_loop::ha47c28576e994db6 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:375 (pubsub+0x000000077981)
    #10 _$LT$ws..io..Handler$LT$F$GT$$GT$::run::h99e1cd80c8146da5 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/io.rs:342 (pubsub+0x00000007cd9f)
    #11 _$LT$ws..WebSocket$LT$F$GT$$GT$::run::hda95d3039f68f2d9 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:308 (pubsub+0x000000074edb)
    #12 _$LT$ws..WebSocket$LT$F$GT$$GT$::listen::h955f903b0018da09 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:289 (pubsub+0x0000000753c6)
    #13 ws::listen::hdb1e06bf70161e00 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/ws-0.6.0/src/lib.rs:79 (pubsub+0x000000072ce8)
    #14 pubsub::serveur_ws::listen_ws::hfbbfb4f08624a769 /home/LUXO/bbigras/dev/rust/pubsub/src/serveur_ws.rs:211 (pubsub+0x0000000f8f44)
    #15 pubsub::main::heea09b5a8c6e3f83 /home/LUXO/bbigras/dev/rust/pubsub/src/main.rs:136 (pubsub+0x0000000fa389)
    #16 __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #17 __libc_start_main <null> (libc.so.6+0x000000020290)

  Thread T15 (tid=23121, running) created by thread T2 at:
    #0 pthread_create /checkout/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:902 (pubsub+0x0000001389b7)
    #1 std::sys::imp::thread::Thread::new::h13e24a45e97a3e79 /checkout/src/libstd/sys/unix/thread.rs:72 (pubsub+0x0000003362d5)
    #2 std::thread::spawn::h65524c6a8920cfe5 /checkout/src/libstd/thread/mod.rs:412 (pubsub+0x000000091fdd)
    #3 hyper::server::listener::spawn_with::hcabe3abce5ee6f54 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/listener.rs:45 (pubsub+0x0000000d0d7c)
    #4 _$LT$hyper..server..listener..ListenerPool$LT$A$GT$$GT$::accept::h3c7fbf392d46a23d /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/listener.rs:31 (pubsub+0x0000000cc67a)
    #5 hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::hffe7344a5446ad53 /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.4/src/server/mod.rs:248 (pubsub+0x0000000d0c02)
    #6 _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h34d5fe9f6f1cbecd /checkout/src/libstd/panic.rs:296 (pubsub+0x0000000f0898)
    #7 std::panicking::try::do_call::h184cebbcfe8628da /checkout/src/libstd/panicking.rs:450 (pubsub+0x0000000932d1)
    #8 __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98 (pubsub+0x00000033e79a)
    #9 std::panic::catch_unwind::h00b52301f14eed71 /checkout/src/libstd/panic.rs:361 (pubsub+0x000000091e80)
    #10 std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h6cbdc2093edccabb /checkout/src/libstd/thread/mod.rs:357 (pubsub+0x000000092cbe)
    #11 _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h2b22dd9fc4327d12 /checkout/src/liballoc/boxed.rs:638 (pubsub+0x0000000c55d8)
    #12 alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:648 (pubsub+0x0000003365d4)
    #13 std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21 (pubsub+0x0000003365d4)
    #14 std::sys::imp::thread::Thread::new::thread_start::h2c901daa88f3cb32 /checkout/src/libstd/sys/unix/thread.rs:84 (pubsub+0x0000003365d4)

SUMMARY: ThreadSanitizer: data race /home/LUXO/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:728 in mio::poll::ReadinessQueue::prepend_readiness_node::h553699cbe5e04d43
==================
```

**Comment by carllerche** [comment]
The `poll.rs` line numbers don't seem to match up w/ the code in the referenced commit. Also `prepend_readiness_node` doesn't exist anymore. Maybe you are still using the old code?

**Comment by brunoqc** [comment]
> Maybe you are still using the old code?

Yes, sorry about that. It looks fine with mio's master branch.
